# Generated by Django 5.2.16 on 2026-07-13 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_shelterprofile_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdopterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('housing_type', models.CharField(blank=True, max_length=40)),
                ('has_yard', models.CharField(blank=True, max_length=10)),
                ('has_screens', models.CharField(blank=True, max_length=10)),
                ('other_pets', models.CharField(blank=True, max_length=255)),
                ('hours_alone', models.CharField(blank=True, max_length=20)),
                ('preferences', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'adopter'}, on_delete=django.db.models.deletion.CASCADE, related_name='adopter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
