# Generated by Django 5.2.16 on 2026-07-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adopterprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopterprofile',
            name='cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
