# Generated by Django 5.2.16 on 2026-07-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='interview_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('approved', 'Aprovado'), ('rejected', 'Recusado')], default='pending', max_length=20),
        ),
    ]
