# Generated by Django 5.2.16 on 2026-07-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_adoptionrequest_interview_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='interview_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='interview_phase',
            field=models.CharField(choices=[('to_schedule', 'Agendar entrevista'), ('scheduled', 'Entrevista agendada'), ('to_perform', 'Realizar entrevista'), ('done', 'Entrevista realizada')], default='to_schedule', max_length=20),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='interview_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
