# Generated by Django 5.2.16 on 2026-07-13 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0003_adoptionrequest_interview_completed_at_and_more'),
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='adopter_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='adopter_cpf',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='has_yard',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='hours_alone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='housing_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='motivation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='other_pets',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='adoptionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'in_progress'])), fields=('adopter', 'animal'), name='unique_active_adoption_request'),
        ),
    ]
