# Generated by Django 5.2.16 on 2026-07-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0004_adoptionrequest_adopter_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='data_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='data_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
