# Generated by Django 5.2.16 on 2026-07-12 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('dog', 'Cão'), ('cat', 'Gato'), ('rabbit', 'Coelho'), ('other', 'Outro')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('age_text', models.CharField(blank=True, max_length=50)),
                ('age_months', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, max_length=30)),
                ('size', models.CharField(blank=True, choices=[('small', 'Pequeno'), ('medium', 'Médio'), ('large', 'Grande')], max_length=20)),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('in_process', 'Em processo'), ('adopted', 'Adotado')], default='available', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('vaccinated', models.BooleanField(default=False)),
                ('neutered', models.BooleanField(default=False)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='accounts.shelterprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimalMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='animals/media/')),
                ('media_type', models.CharField(choices=[('photo', 'Foto'), ('video', 'Vídeo')], default='photo', max_length=10)),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='animals.animal')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
