# Generated by Django 5.2.16 on 2026-07-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Macho'), ('female', 'Fêmea')], max_length=10),
        ),
    ]
